### ISSUE TITLE
Claim all button for gifts

### ISSUE THREAD

**Issue by TheBaconSpace** [EZFNDEV/FNPrivateServer#9]
Would love a way to have a claim all button if you get stuck in a gifting loop

**Comment by zappy-b00ted-u** [comment]
how do you even get the gifts please explain

**Comment by TheBaconSpace** [comment]
![](http://puu.sh/GLMKX/835304d6e1.png)
This is how

**Comment by VestigeNet** [comment]
Sorry but the gifting is fake it is not permanent no way plus it is only client side. Im pretty sure its a rat as well the dll are fake
